<a href="https://colab.research.google.com/github/GabrielStamfordDev/Data-Science-First-Steps/blob/main/Lesson04/Alura_04_Transfomacao_Manipulacao_Dados_desafio_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_json('/content/dados_vendas_clientes.json')
df.head()

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [ ]:
df = pd.json_normalize(df['dados_vendas'])
df.head()

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [ ]:
columns = list(df.columns)
df = df.explode(columns[1:])
df

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31
1    07/06/2022  Isabely JOanes 738       R$ 168,07
1    07/06/2022  Isabely JOanes 738       R$ 339,18
1    07/06/2022  Isabely JOanes 738       R$ 314,69
2    08/06/2022  Isabely JOanes 738       R$ 682,05
2    08/06/2022    JOãO Gabriel 671       R$ 386,34
2    08/06/2022  Julya meireles 914       R$ 622,65
2    08/06/2022  Julya meireles 914       R$ 630,79
3    09/06/2022  Julya meireles 914        R$ 390,3
3    09/06/2022     MaRIA Julia 444       R$ 759,16
3    09/06/2022     MaRIA Julia 444       R$ 334,47
3    09/06/2022     MaRIA Julia 444       R$ 678,78
4    10/06/2022     MaRIA Julia 444       R$ 314,24
4    10/06/2022     PEDRO PASCO 812       R$ 311,15
4    10/06/2022    Paulo castro 481       R$ 899,16
4    10/06/2022   Thiago fritzz 883       R$ 885,24

In [ ]:
df.reset_index(inplace = True, drop = True)

In [ ]:
df

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [ ]:
df['Valor da compra'] = df['Valor da compra'].apply(lambda x : x.replace('R$ ', '').replace(',', '.').strip())
df

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321           836.5
1     06/06/2022  DieGO ARMANDIU 210          573.33
2     06/06/2022  DieGO ARMANDIU 210           392.8
3     06/06/2022  DieGO ARMANDIU 210          512.34
4     07/06/2022  Isabely JOanes 738          825.31
5     07/06/2022  Isabely JOanes 738          168.07
6     07/06/2022  Isabely JOanes 738          339.18
7     07/06/2022  Isabely JOanes 738          314.69
8     08/06/2022  Isabely JOanes 738          682.05
9     08/06/2022    JOãO Gabriel 671          386.34
10    08/06/2022  Julya meireles 914          622.65
11    08/06/2022  Julya meireles 914          630.79
12    09/06/2022  Julya meireles 914           390.3
13    09/06/2022     MaRIA Julia 444          759.16
14    09/06/2022     MaRIA Julia 444          334.47
15    09/06/2022     MaRIA Julia 444          678.78
16    10/06/2022     MaRIA Julia 444          314.24
17    10/06/2022     PEDRO PASCO 812          311.15
18    10/06/2022    Paulo castro 481          899.16
19    10/06/2022   Thiago fritzz 883          885.24

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [ ]:
df['Valor da compra'] = df['Valor da compra'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

In [ ]:
df['Cliente'] = df['Cliente'].str.lower()
df['Cliente'] = df['Cliente'].replace(r'[^a-z\s]', '' , regex = True)
df.head()

  Data de venda          Cliente  Valor da compra
0    06/06/2022       ana lucia            836.50
1    06/06/2022  diego armandiu            573.33
2    06/06/2022  diego armandiu            392.80
3    06/06/2022  diego armandiu            512.34
4    07/06/2022  isabely joanes            825.31

In [ ]:
df['Data de venda'] = pd.to_datetime(df['Data de venda'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes

In [ ]:
df.head()

  Data de venda          Cliente  Valor da compra
0    2022-06-06       ana lucia            836.50
1    2022-06-06  diego armandiu            573.33
2    2022-06-06  diego armandiu            392.80
3    2022-06-06  diego armandiu            512.34
4    2022-07-06  isabely joanes            825.31

In [ ]:
df['Data de venda'].dt.strftime('%m/%Y')

0     06/2022
1     06/2022
2     06/2022
3     06/2022
4     07/2022
5     07/2022
6     07/2022
7     07/2022
8     08/2022
9     08/2022
10    08/2022
11    08/2022
12    09/2022
13    09/2022
14    09/2022
15    09/2022
16    10/2022
17    10/2022
18    10/2022
19    10/2022
Name: Data de venda, dtype: object

In [ ]:
compras_por_mes = df.groupby(df['Data de venda'].dt.strftime('%m/%Y'))[['Valor da compra']].sum()
compras_por_mes

               Valor da compra
Data de venda
06/2022                2314.97
07/2022                1647.25
08/2022                2321.83
09/2022                2162.71
10/2022                2409.79

In [ ]:
compra_por_cliente = df.groupby(df['Cliente'])[['Valor da compra']].sum()
compra_por_cliente

                 Valor da compra
Cliente
ana lucia                 836.50
diego armandiu           1478.47
isabely joanes           2329.30
joo gabriel               386.34
julya meireles           1643.74
maria julia              2086.65
paulo castro              899.16
pedro pasco               311.15
thiago fritzz             885.24