<a href="https://colab.research.google.com/github/GabrielStamfordDev/Data-Science-First-Steps/blob/main/Lesson04/Alura_04_Transfomacao_Manipulacao_Dados_desafio_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_json('/content/dados_locacao_imoveis.json')
df.head()

                                       dados_locacao
0  {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1  {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2  {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3  {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4  {'apartamento': 'C301 (blocoAP)', 'datas_combi...

In [ ]:
df = pd.json_normalize(df['dados_locacao'])
df.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"

In [ ]:
columns = list(df.columns)
df = df.explode(columns[1:])
df

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
1,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
2,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
2,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
3,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
3,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
4,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
4,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
5,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
5,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
6,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
6,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
7,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
7,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
8,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
8,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
9,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
9,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
10,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
10,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
11,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
11,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
12,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
12,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
13,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
13,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
14,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
14,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [ ]:
df.reset_index(inplace = True, drop = True)
df.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"

In [ ]:
df['valor_aluguel'] = df['valor_aluguel'].apply(lambda x : x.replace('$ ', '').replace(',', '.').replace(' reais', '').strip())
df.head()

      apartamento datas_combinadas_pagamento datas_de_pagamento valor_aluguel
0  A101 (blocoAP)                 01/06/2022         05/06/2022        1000.0
1  A101 (blocoAP)                 01/07/2022         03/07/2022        2500.0
2  A102 (blocoAP)                 02/06/2022         02/06/2022        1100.0
3  A102 (blocoAP)                 02/07/2022         06/07/2022        2600.0
4  B201 (blocoAP)                 03/06/2022         07/06/2022        1200.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [ ]:
df['valor_aluguel'] = df['valor_aluguel'].astype(float)
df.head()

      apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0  A101 (blocoAP)                 01/06/2022         05/06/2022         1000.0
1  A101 (blocoAP)                 01/07/2022         03/07/2022         2500.0
2  A102 (blocoAP)                 02/06/2022         02/06/2022         1100.0
3  A102 (blocoAP)                 02/07/2022         06/07/2022         2600.0
4  B201 (blocoAP)                 03/06/2022         07/06/2022         1200.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

In [ ]:
df['apartamento'] = df['apartamento'].str.replace('(blocoAP)', '')
df['apartamento'] = df['apartamento'].str.strip()
# dados['apartamento'] = dados['apartamento'].str.replace(r' \(blocoAP\)', '', regex=True)
df.head()

  apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                 01/06/2022         05/06/2022         1000.0
1        A101                 01/07/2022         03/07/2022         2500.0
2        A102                 02/06/2022         02/06/2022         1100.0
3        A102                 02/07/2022         06/07/2022         2600.0
4        B201                 03/06/2022         07/06/2022         1200.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

In [ ]:
df['datas_combinadas_pagamento'] = pd.to_datetime(df['datas_combinadas_pagamento'], format='%d/%m/%Y')
df['datas_de_pagamento'] = pd.to_datetime(df['datas_de_pagamento'], format='%d/%m/%Y')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     datetime64[ns]
 2   datas_de_pagamento          30 non-null     datetime64[ns]
 3   valor_aluguel               30 non-null     float64
dtypes: datetime64[ns](2), float64(1), object(1)
memory usage: 1.1+ KB

In [ ]:
(df['datas_de_pagamento'] > df['datas_combinadas_pagamento'])
df[df['datas_de_pagamento'] > df['datas_combinadas_pagamento']]

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0         A101                 2022-06-01         2022-06-05         1000.0
1         A101                 2022-07-01         2022-07-03         2500.0
3         A102                 2022-07-02         2022-07-06         2600.0
4         B201                 2022-06-03         2022-06-07         1200.0
6         B202                 2022-06-04         2022-06-07         1300.0
7         B202                 2022-07-04         2022-07-05         2800.0
8         C301                 2022-06-05         2022-06-10         1400.0
9         C301                 2022-07-05         2022-07-09         2900.0
10        C302                 2022-06-06         2022-06-08         1500.0
11        C302                 2022-07-06         2022-07-12         1200.0
13        D401                 2022-07-07         2022-07-09         1300.0
14        D402                 2022-06-08         2022-06-10         1700.0
15        D402                 2022-07-08         2022-07-14         1400.0
16        E501                 2022-06-09         2022-06-10         1800.0
18        E502                 2022-06-10         2022-06-16         1900.0
19        E502                 2022-07-10         2022-07-12         1600.0
20        F601                 2022-06-11         2022-06-17         2000.0
21        F601                 2022-07-11         2022-07-13         1000.0
22        F602                 2022-06-12         2022-06-15         2100.0
24        G701                 2022-06-13         2022-06-19         2200.0
25        G701                 2022-07-13         2022-07-20         1200.0
26        G702                 2022-06-14         2022-06-15         2300.0
27        G702                 2022-07-14         2022-07-17         2100.0
28        H801                 2022-06-15         2022-06-18         2400.0
29        H801                 2022-07-15         2022-07-16         2200.0

In [ ]:
df['atrasos'] = (df['datas_de_pagamento'] - df['datas_combinadas_pagamento']).dt.days
df.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atrasos
0,A101,2022-06-01,2022-06-05,1000.0,4
1,A101,2022-07-01,2022-07-03,2500.0,2
2,A102,2022-06-02,2022-06-02,1100.0,0
3,A102,2022-07-02,2022-07-06,2600.0,4
4,B201,2022-06-03,2022-06-07,1200.0,4

In [ ]:
df['atrasos'].mean()

np.float64(2.8666666666666667)

In [ ]:
media_atraso_apt = df.groupby(df['apartamento'])[['atrasos']].mean()
media_atraso_apt

             atrasos
apartamento
A101             3.0
A102             2.0
B201             2.0
B202             2.0
C301             4.5
C302             4.0
D401             1.0
D402             4.0
E501             0.5
E502             4.0
F601             4.0
F602             1.5
G701             6.5
G702             2.0
H801             2.0